### ISSUE TITLE
KeyError: 'TINYMCE_SETUP_JS' while running migrate

### ISSUE THREAD

**Issue by just10minutes** [hicham-elmansouri/django-happystamp#2]
I followed the instructions as specified, ended up with below error during the migrate phase.

Am I doing something wrong?

Below is the traceback: 
Django version 1.11
OS : Ubuntu 14.04

```
(loyalty) osboxes@osboxes:~/Desktop/Projects/loyalty/projects/myloyalty$ python manage.py migrate
Traceback (most recent call last):
  File "/home/osboxes/Desktop/Projects/loyalty/lib/python3.5/site-packages/mezzanine/conf/__init__.py", line 231, in __getattr__
    setting = registry[name]
KeyError: 'TINYMCE_SETUP_JS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/osboxes/Desktop/Projects/loyalty/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/osboxes/Desktop/Projects/loyalty/lib/python3.5/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/home/osboxes/Desktop/Projects/loyalty/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/osboxes/Desktop/Projects/loyalty/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/osboxes/Desktop/Projects/loyalty/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/osboxes/Desktop/Projects/loyalty/lib/python3.5/site-packages/happystamp/models.py", line 15, in <module>
    from mezzanine.core.models import Displayable
  File "/home/osboxes/Desktop/Projects/loyalty/lib/python3.5/site-packages/mezzanine/core/models.py", line 24, in <module>
    from mezzanine.core.fields import RichTextField, OrderField
  File "/home/osboxes/Desktop/Projects/loyalty/lib/python3.5/site-packages/mezzanine/core/fields.py", line 12, in <module>
    from mezzanine.core.forms import OrderWidget
  File "/home/osboxes/Desktop/Projects/loyalty/lib/python3.5/site-packages/mezzanine/core/forms.py", line 40, in <module>
    class TinyMceWidget(forms.Textarea):
  File "/home/osboxes/Desktop/Projects/loyalty/lib/python3.5/site-packages/mezzanine/core/forms.py", line 46, in TinyMceWidget
    class Media:
  File "/home/osboxes/Desktop/Projects/loyalty/lib/python3.5/site-packages/mezzanine/core/forms.py", line 49, in Media
    static(settings.TINYMCE_SETUP_JS)]
  File "/home/osboxes/Desktop/Projects/loyalty/lib/python3.5/site-packages/mezzanine/conf/__init__.py", line 233, in __getattr__
    return getattr(django_settings, name)
  File "/home/osboxes/Desktop/Projects/loyalty/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'TINYMCE_SETUP_JS'
```

**Comment by hicham-elmansouri** [comment]
Hello,
It looks like it's a mezzanine issue : http://mezzanine.jupo.org/docs/configuration.html

**Comment by just10minutes** [comment]
Hi Hicham,

Does it mean I need to create one defaults.py for happystamp.

Thanks
